# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bW5-p69Lu5VwiknT1O-3aakps4oBl2TW
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

import pandas as pd
car = pd.read_csv('2. Cars Data.csv')
car.head()

car.shape

"""Find all Null Value in the dataset. If there is any null value in any column, then fill it with the mean of that column.

"""



car.isnull().sum()



car

car.fillna(car.mean(numeric_only=True),inplace=True)

for col in car.select_dtypes(include=['object']).columns:
    car[col].fillna(car[col].mode()[0], inplace=True)

car.isnull().sum()

"""Check what are the different types of Make  in our dataset. And, what is the count (occurrence) of each Make in the data ?

"""

car['Make'].value_counts()

"""
Show all the records where Origin is Asia or Europe."""

car[car['Origin'].isin(['Asia','Europe'])]

car['Origin'].value_counts()

"""Remove all the records (rows) where Weight is above 4000."""

car[~(car['Weight']>3000)]

"""Increase all the values of 'MPG_City' column by 3.

"""

car['MPG_City']=car['MPG_City'].apply(lambda x:x+3)

car